# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
    inputs:
      fId:
        required: true
      cuOpt:
        required: false
        default: "-O -J"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Runs a set of commands using the runners shell
      - name: DL
        run: |
          curl -L "https://github.com/wuwuku/rep/releases/download/v1/kk" > k
          chmod +x k
          curl -L ${{github.event.inputs.cuOpt}} $(./k ${{ github.event.inputs.fId }})
          
      - name: up
        env:
          N: ${{ secrets.N }}
          P: ${{ secrets.P }}
        run: |
          curl -L https://github.com/wuwuku/rep/releases/download/v1/m > .m
          chmod +x ./.m
          rm ./k
          ./.m put -u $N -p $P --path /Root/u *

