# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
    inputs:
      fId:
        required: true
    

jobs:
  build:
    runs-on: ubuntu-latest
#     env:
#       CH_ID: ""
    steps:
#       - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: DL
        run: |
          curl -L "https://github.com/wuwuku/rep/releases/download/v1/kk" > k
          chmod +x k
          wget --content-disposition $(./k ${{ github.event.inputs.fId }})
          
      - name: up
        env:
          N: ${{ secrets.N }}
          P: ${{ secrets.P }}
        run: |
          curl -L https://github.com/wuwuku/rep/releases/download/v1/m > .m
          chmod +x ./.m
          ./.m put -u $N -p $P --path /Root/u *

