name: C

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
        u:
          required: true
          
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run a one-line script
        run:  |
          ${{ github.event.inputs.u }} -L > f.out
          
      - name: up
        env:
          N: ${{ secrets.N }}
          P: ${{ secrets.P }}
        run: |
          sudo apt install megatools
          megacopy -u $N -p $P -l ./ -r /u
          
