# This is a basic workflow to help you get started with Actions

name: J

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    
#     container:
#       image: jaymoulin/jdownloader
#       env:
#         MYJD_USER: ${{ secrets.MYJD_USER }}
#         MYJD_PASSWORD: ${{ secrets.MYJD_PASSWORD }}
#         MYJD_DEVICE_NAME: github
#       ports:
#         - 3129:3129
    steps:
      - name: Check out the repo
        run: |
          cd $HOME
          mkdir dl
          mkdir cfg
          docker run -d --init --restart=always -v $HOME/dl:/opt/JDownloader/Downloads -v $HOME/cfg:/opt/JDownloader/app/cfg --name jdownloader -u $(id -u) -p 3129:3129 -e MYJD_USER=${{ secrets.MYJD_USER }} -e MYJD_PASSWORD=${{ secrets.MYJD_PASSWORD }} -e MYJD_DEVICE_NAME=github jaymoulin/jdownloader
          sleep 20000
