name: T

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
        u:
          required: true
          
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run a one-line script
        run:  |
          sudo apt-get install transmission-cli
          transmission-cli "${{ github.event.inputs.u }}"
          
      - uses: actions/upload-artifact@v2
        with:
          path: ./
