# This is a basic workflow to help you get started with Actions

name: Y

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
        u:
          required: true
          
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run a one-line script
        run:  |
          curl -L https://yt-dl.org/downloads/latest/youtube-dl > d
          chmod +x ./d
          ./d --list-formats "${{ github.event.inputs.u }}"
